[package]
name = "xtask"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
fs_extra = "1.2"
serde = { version = "1.0", features = ["derive"] }
structopt = { version = "0.3", default-features = false }
sudo = "0.6"
tera = "1.12"
thiserror = "1.0"
