name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Install dapper
      run: go install github.com/rancher/dapper@latest
    - name: Build
      run: dapper cargo build
    - name: Test
      run: dapper cargo test
    - name: Lint
      run: dapper cargo clippy -- -D warnings
    - name: Build book
      run: ./scripts/mdbook.sh
