# Deployments which should run successfully as they should not violate policy
# levels of their namespaces.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default-success
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-default-success
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-default-success
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:1.21.4
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-restricted-success
  namespace: restricted
spec:
  selector:
    matchLabels:
      app: nginx-restricted-success
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-restricted-success
    spec:
      securityContext:
        runAsUser: 101
        seccompProfile:
          type: "RuntimeDefault"
      containers:
      - name: nginx
        image: bitnami/nginx:1.21.4
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-baseline-success
  namespace: baseline
spec:
  selector:
    matchLabels:
      app: nginx-baseline-success
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-baseline-success
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx:1.21.4
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpf-privileged-success
  namespace: privileged
spec:
  selector:
    matchLabels:
      app: bpf-privileged-success
  replicas: 1
  template:
    metadata:
      labels:
        app: bpf-privileged-success
    spec:
      containers:
      - name: bpf
        image: busybox:latest
        command: ["sleep"]
        args: ["inf"]
        volumeMounts:
        - name: bpffs
          mountPath: /sys/fs/bpf
      volumes:
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
          type: Directory
